version: '3.8'

services:
  scylla:
    build:
      context: .
      # dockerfile: Dockerfile-alpine
      # target: prod
    volumes:
      - /var/www/scylla:/var/www/scylla
    ports:
      - "8899:8899"
      - "8081:8081"
